- name: install elastic stack for ubuntu
  apt:
    name:
      - elasticsearch
      - kibana
      - logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install elastic stack for centos
  dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
